apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwebapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TestWebApi
  template:
    metadata:
      labels:
        app: TestWebApi
    spec:
      containers:
      - name: 848863DNAzureACR
        image: 848863dnazureacr.azurecr.io/dnrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn2

---
apiVersion: v1
kind: Service
metadata:
  name: TestWebApi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: TestWebApi


